[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200

build_flags =
    -DBUFFER_LENGTH=256
    -DTWI_BUFFER_LENGTH=256

lib_deps =
    fastled/FastLED @ ^3.9.15
    nanopb/Nanopb @ ^0.4.9