/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CATAN_CATAN_PB_H_INCLUDED
#define PB_CATAN_CATAN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _catan_GamePhase {
    catan_GamePhase_PHASE_LOBBY = 0,
    catan_GamePhase_PHASE_BOARD_SETUP = 1,
    catan_GamePhase_PHASE_NUMBER_REVEAL = 2,
    catan_GamePhase_PHASE_INITIAL_PLACEMENT = 3,
    catan_GamePhase_PHASE_PLAYING = 4,
    catan_GamePhase_PHASE_ROBBER = 5,
    catan_GamePhase_PHASE_GAME_OVER = 6
} catan_GamePhase;

typedef enum _catan_PlayerAction {
    catan_PlayerAction_ACTION_NONE = 0,
    catan_PlayerAction_ACTION_READY = 1,
    catan_PlayerAction_ACTION_START_GAME = 2,
    catan_PlayerAction_ACTION_NEXT_NUMBER = 3,
    catan_PlayerAction_ACTION_PLACE_DONE = 4,
    catan_PlayerAction_ACTION_ROLL_DICE = 5,
    catan_PlayerAction_ACTION_END_TURN = 6,
    catan_PlayerAction_ACTION_SKIP_ROBBER = 7,
    catan_PlayerAction_ACTION_REPORT = 8,
    catan_PlayerAction_ACTION_REQUEST_SYNC = 9 /* asks the board to resend a full state snapshot */
} catan_PlayerAction;

/* MessageType mirrors the Envelope.body oneof discriminant for easy logging
 and routing without needing to inspect the oneof tag. The numeric values
 match the field tag of the corresponding body entry. */
typedef enum _catan_MessageType {
    catan_MessageType_MSG_UNSPECIFIED = 0,
    catan_MessageType_MSG_BOARD_STATE = 10,
    catan_MessageType_MSG_PLAYER_INPUT = 11,
    catan_MessageType_MSG_ACK = 12,
    catan_MessageType_MSG_NACK = 13,
    catan_MessageType_MSG_SYNC_REQUEST = 14
} catan_MessageType;

typedef enum _catan_NackReason {
    catan_NackReason_NACK_UNKNOWN = 0,
    catan_NackReason_NACK_BAD_PROTO = 1,
    catan_NackReason_NACK_BAD_STATE = 2,
    catan_NackReason_NACK_OUT_OF_TURN = 3,
    catan_NackReason_NACK_INVALID_PLACEMENT = 4,
    catan_NackReason_NACK_UNKNOWN_SENDER = 5
} catan_NackReason;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(19) catan_BoardState_tiles_packed_t;
typedef struct _catan_BoardState {
    catan_GamePhase phase;
    uint32_t num_players;
    uint32_t current_player;
    uint32_t setup_round;
    bool has_rolled;
    uint32_t die1;
    uint32_t die2;
    uint32_t reveal_number;
    uint32_t winner_id;
    uint32_t robber_tile;
    uint32_t connected_mask;
    catan_BoardState_tiles_packed_t tiles_packed; /* 19 bytes, one per tile (see above) */
    pb_size_t vp_count;
    uint32_t vp[4]; /* self-reported VP per player, max 4 */
} catan_BoardState;

typedef struct _catan_PlayerInput {
    uint32_t player_id;
    catan_PlayerAction action;
    /* Fields below populated only for ACTION_REPORT. */
    uint32_t vp;
    uint32_t res_lumber;
    uint32_t res_wool;
    uint32_t res_grain;
    uint32_t res_brick;
    uint32_t res_ore;
} catan_PlayerInput;

/* Positive acknowledgement — sent by the receiver of a reliable Envelope.
 Identifies the original (sender, seq) being acked. The ack itself carries
 its own sender_id/sequence_number in its Envelope, but is never reliable. */
typedef struct _catan_Ack {
    uint32_t ack_sender;
    uint32_t ack_seq;
} catan_Ack;

/* Negative acknowledgement — sent instead of Ack when the receiver rejects
 a reliable Envelope. The sender SHOULD NOT retransmit. */
typedef struct _catan_Nack {
    uint32_t ack_sender;
    uint32_t ack_seq;
    catan_NackReason reason;
} catan_Nack;

/* Station or mobile client asking the board for a full state snapshot.
 `last_seen_seq` is informational (Phase 1 always responds with a full
 BoardState on the next tick). */
typedef struct _catan_SyncRequest {
    uint32_t last_seen_seq;
} catan_SyncRequest;

/* Common transport metadata for every wire message. All fields except `body`
 are required-by-convention (not by proto3) and validated by receivers.

   proto_version    = CATAN_PROTO_VERSION (currently 4). Receivers drop
                      envelopes with a different version.
   sender_id        = CATAN_NODE_* constant identifying the originator.
   sequence_number  = monotonic per-sender counter starting at 1. Resets on
                      reboot; receivers treat sequence_number <= last_seen
                      (from the same sender) as a duplicate and drop it.
   timestamp_ms     = sender-local millis() at emit time.
   message_type     = duplicates the body oneof discriminant.
   reliable         = if true, the receiver responds with Ack/Nack. */
typedef struct _catan_Envelope {
    uint32_t proto_version;
    uint32_t sender_id;
    uint32_t sequence_number;
    uint32_t timestamp_ms;
    catan_MessageType message_type;
    bool reliable;
    pb_size_t which_body;
    union {
        catan_BoardState board_state;
        catan_PlayerInput player_input;
        catan_Ack ack;
        catan_Nack nack;
        catan_SyncRequest sync_request;
    } body;
} catan_Envelope;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _catan_GamePhase_MIN catan_GamePhase_PHASE_LOBBY
#define _catan_GamePhase_MAX catan_GamePhase_PHASE_GAME_OVER
#define _catan_GamePhase_ARRAYSIZE ((catan_GamePhase)(catan_GamePhase_PHASE_GAME_OVER+1))

#define _catan_PlayerAction_MIN catan_PlayerAction_ACTION_NONE
#define _catan_PlayerAction_MAX catan_PlayerAction_ACTION_REQUEST_SYNC
#define _catan_PlayerAction_ARRAYSIZE ((catan_PlayerAction)(catan_PlayerAction_ACTION_REQUEST_SYNC+1))

#define _catan_MessageType_MIN catan_MessageType_MSG_UNSPECIFIED
#define _catan_MessageType_MAX catan_MessageType_MSG_SYNC_REQUEST
#define _catan_MessageType_ARRAYSIZE ((catan_MessageType)(catan_MessageType_MSG_SYNC_REQUEST+1))

#define _catan_NackReason_MIN catan_NackReason_NACK_UNKNOWN
#define _catan_NackReason_MAX catan_NackReason_NACK_UNKNOWN_SENDER
#define _catan_NackReason_ARRAYSIZE ((catan_NackReason)(catan_NackReason_NACK_UNKNOWN_SENDER+1))

#define catan_BoardState_phase_ENUMTYPE catan_GamePhase

#define catan_PlayerInput_action_ENUMTYPE catan_PlayerAction


#define catan_Nack_reason_ENUMTYPE catan_NackReason


#define catan_Envelope_message_type_ENUMTYPE catan_MessageType


/* Initializer values for message structs */
#define catan_BoardState_init_default            {_catan_GamePhase_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, {0, 0, 0, 0}}
#define catan_PlayerInput_init_default           {0, _catan_PlayerAction_MIN, 0, 0, 0, 0, 0, 0}
#define catan_Ack_init_default                   {0, 0}
#define catan_Nack_init_default                  {0, 0, _catan_NackReason_MIN}
#define catan_SyncRequest_init_default           {0}
#define catan_Envelope_init_default              {0, 0, 0, 0, _catan_MessageType_MIN, 0, 0, {catan_BoardState_init_default}}
#define catan_BoardState_init_zero               {_catan_GamePhase_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, {0, 0, 0, 0}}
#define catan_PlayerInput_init_zero              {0, _catan_PlayerAction_MIN, 0, 0, 0, 0, 0, 0}
#define catan_Ack_init_zero                      {0, 0}
#define catan_Nack_init_zero                     {0, 0, _catan_NackReason_MIN}
#define catan_SyncRequest_init_zero              {0}
#define catan_Envelope_init_zero                 {0, 0, 0, 0, _catan_MessageType_MIN, 0, 0, {catan_BoardState_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define catan_BoardState_phase_tag               2
#define catan_BoardState_num_players_tag         3
#define catan_BoardState_current_player_tag      4
#define catan_BoardState_setup_round_tag         5
#define catan_BoardState_has_rolled_tag          6
#define catan_BoardState_die1_tag                7
#define catan_BoardState_die2_tag                8
#define catan_BoardState_reveal_number_tag       9
#define catan_BoardState_winner_id_tag           10
#define catan_BoardState_robber_tile_tag         11
#define catan_BoardState_connected_mask_tag      12
#define catan_BoardState_tiles_packed_tag        13
#define catan_BoardState_vp_tag                  14
#define catan_PlayerInput_player_id_tag          1
#define catan_PlayerInput_action_tag             2
#define catan_PlayerInput_vp_tag                 10
#define catan_PlayerInput_res_lumber_tag         11
#define catan_PlayerInput_res_wool_tag           12
#define catan_PlayerInput_res_grain_tag          13
#define catan_PlayerInput_res_brick_tag          14
#define catan_PlayerInput_res_ore_tag            15
#define catan_Ack_ack_sender_tag                 1
#define catan_Ack_ack_seq_tag                    2
#define catan_Nack_ack_sender_tag                1
#define catan_Nack_ack_seq_tag                   2
#define catan_Nack_reason_tag                    3
#define catan_SyncRequest_last_seen_seq_tag      1
#define catan_Envelope_proto_version_tag         1
#define catan_Envelope_sender_id_tag             2
#define catan_Envelope_sequence_number_tag       3
#define catan_Envelope_timestamp_ms_tag          4
#define catan_Envelope_message_type_tag          5
#define catan_Envelope_reliable_tag              6
#define catan_Envelope_board_state_tag           10
#define catan_Envelope_player_input_tag          11
#define catan_Envelope_ack_tag                   12
#define catan_Envelope_nack_tag                  13
#define catan_Envelope_sync_request_tag          14

/* Struct field encoding specification for nanopb */
#define catan_BoardState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    phase,             2) \
X(a, STATIC,   SINGULAR, UINT32,   num_players,       3) \
X(a, STATIC,   SINGULAR, UINT32,   current_player,    4) \
X(a, STATIC,   SINGULAR, UINT32,   setup_round,       5) \
X(a, STATIC,   SINGULAR, BOOL,     has_rolled,        6) \
X(a, STATIC,   SINGULAR, UINT32,   die1,              7) \
X(a, STATIC,   SINGULAR, UINT32,   die2,              8) \
X(a, STATIC,   SINGULAR, UINT32,   reveal_number,     9) \
X(a, STATIC,   SINGULAR, UINT32,   winner_id,        10) \
X(a, STATIC,   SINGULAR, UINT32,   robber_tile,      11) \
X(a, STATIC,   SINGULAR, UINT32,   connected_mask,   12) \
X(a, STATIC,   SINGULAR, BYTES,    tiles_packed,     13) \
X(a, STATIC,   REPEATED, UINT32,   vp,               14)
#define catan_BoardState_CALLBACK NULL
#define catan_BoardState_DEFAULT NULL

#define catan_PlayerInput_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   player_id,         1) \
X(a, STATIC,   SINGULAR, UENUM,    action,            2) \
X(a, STATIC,   SINGULAR, UINT32,   vp,               10) \
X(a, STATIC,   SINGULAR, UINT32,   res_lumber,       11) \
X(a, STATIC,   SINGULAR, UINT32,   res_wool,         12) \
X(a, STATIC,   SINGULAR, UINT32,   res_grain,        13) \
X(a, STATIC,   SINGULAR, UINT32,   res_brick,        14) \
X(a, STATIC,   SINGULAR, UINT32,   res_ore,          15)
#define catan_PlayerInput_CALLBACK NULL
#define catan_PlayerInput_DEFAULT NULL

#define catan_Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ack_sender,        1) \
X(a, STATIC,   SINGULAR, UINT32,   ack_seq,           2)
#define catan_Ack_CALLBACK NULL
#define catan_Ack_DEFAULT NULL

#define catan_Nack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ack_sender,        1) \
X(a, STATIC,   SINGULAR, UINT32,   ack_seq,           2) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            3)
#define catan_Nack_CALLBACK NULL
#define catan_Nack_DEFAULT NULL

#define catan_SyncRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   last_seen_seq,     1)
#define catan_SyncRequest_CALLBACK NULL
#define catan_SyncRequest_DEFAULT NULL

#define catan_Envelope_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_version,     1) \
X(a, STATIC,   SINGULAR, UINT32,   sender_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   sequence_number,   3) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      4) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,      5) \
X(a, STATIC,   SINGULAR, BOOL,     reliable,          6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,board_state,body.board_state),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,player_input,body.player_input),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,ack,body.ack),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,nack,body.nack),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (body,sync_request,body.sync_request),  14)
#define catan_Envelope_CALLBACK NULL
#define catan_Envelope_DEFAULT NULL
#define catan_Envelope_body_board_state_MSGTYPE catan_BoardState
#define catan_Envelope_body_player_input_MSGTYPE catan_PlayerInput
#define catan_Envelope_body_ack_MSGTYPE catan_Ack
#define catan_Envelope_body_nack_MSGTYPE catan_Nack
#define catan_Envelope_body_sync_request_MSGTYPE catan_SyncRequest

extern const pb_msgdesc_t catan_BoardState_msg;
extern const pb_msgdesc_t catan_PlayerInput_msg;
extern const pb_msgdesc_t catan_Ack_msg;
extern const pb_msgdesc_t catan_Nack_msg;
extern const pb_msgdesc_t catan_SyncRequest_msg;
extern const pb_msgdesc_t catan_Envelope_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define catan_BoardState_fields &catan_BoardState_msg
#define catan_PlayerInput_fields &catan_PlayerInput_msg
#define catan_Ack_fields &catan_Ack_msg
#define catan_Nack_fields &catan_Nack_msg
#define catan_SyncRequest_fields &catan_SyncRequest_msg
#define catan_Envelope_fields &catan_Envelope_msg

/* Maximum encoded size of messages (where known) */
#define CATAN_CATAN_PB_H_MAX_SIZE                catan_Envelope_size
#define catan_Ack_size                           12
#define catan_BoardState_size                    103
#define catan_Envelope_size                      133
#define catan_Nack_size                          14
#define catan_PlayerInput_size                   44
#define catan_SyncRequest_size                   6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
