/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "catan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(catan_BoardState, catan_BoardState, AUTO)


PB_BIND(catan_PlayerInput, catan_PlayerInput, AUTO)


PB_BIND(catan_Ack, catan_Ack, AUTO)


PB_BIND(catan_Nack, catan_Nack, AUTO)


PB_BIND(catan_SyncRequest, catan_SyncRequest, AUTO)


PB_BIND(catan_Envelope, catan_Envelope, AUTO)











