/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CATAN_CATAN_PB_H_INCLUDED
#define PB_CATAN_CATAN_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _catan_GamePhase {
    catan_GamePhase_PHASE_LOBBY = 0,
    catan_GamePhase_PHASE_BOARD_SETUP = 1,
    catan_GamePhase_PHASE_NUMBER_REVEAL = 2,
    catan_GamePhase_PHASE_INITIAL_PLACEMENT = 3,
    catan_GamePhase_PHASE_PLAYING = 4,
    catan_GamePhase_PHASE_ROBBER = 5,
    catan_GamePhase_PHASE_GAME_OVER = 6
} catan_GamePhase;

typedef enum _catan_PlayerAction {
    catan_PlayerAction_ACTION_NONE = 0,
    catan_PlayerAction_ACTION_READY = 1,
    catan_PlayerAction_ACTION_START_GAME = 2,
    catan_PlayerAction_ACTION_NEXT_NUMBER = 3,
    catan_PlayerAction_ACTION_PLACE_DONE = 4,
    catan_PlayerAction_ACTION_ROLL_DICE = 5,
    catan_PlayerAction_ACTION_END_TURN = 6,
    catan_PlayerAction_ACTION_SKIP_ROBBER = 7,
    catan_PlayerAction_ACTION_REPORT = 8
} catan_PlayerAction;

/* Struct definitions */
typedef PB_BYTES_ARRAY_T(19) catan_BoardState_tiles_packed_t;
typedef struct _catan_BoardState {
    uint32_t proto_version;
    catan_GamePhase phase;
    uint32_t num_players;
    uint32_t current_player;
    uint32_t setup_round;
    bool has_rolled;
    uint32_t die1;
    uint32_t die2;
    uint32_t reveal_number;
    uint32_t winner_id; /* 0xFF if no winner yet */
    uint32_t robber_tile; /* 0xFF if unplaced */
    uint32_t connected_mask; /* bit i set => player i has a phone connected */
    catan_BoardState_tiles_packed_t tiles_packed; /* 19 bytes, one per tile (see above) */
    pb_size_t vp_count;
    uint32_t vp[4]; /* self-reported VP per player, max 4 */
    pb_size_t ready_count;
    uint32_t ready[4]; /* 0/1 ready flag per player slot, max 4 */
} catan_BoardState;

typedef struct _catan_PlayerInput {
    uint32_t proto_version;
    uint32_t player_id;
    catan_PlayerAction action;
    /* Optional stable identifier of the originating mobile device. The hub
 already tags every input with the authoritative player_id derived from
 the BLE connection slot, so client_id is informational only (used by
 the Mega for diagnostics and by the hub for slot persistence). */
    char client_id[40];
    /* Fields below populated only for ACTION_REPORT. */
    uint32_t vp;
    uint32_t res_lumber;
    uint32_t res_wool;
    uint32_t res_grain;
    uint32_t res_brick;
    uint32_t res_ore;
} catan_PlayerInput;

/* PlayerPresence — sent by the hub to the Mega whenever the set of
 connected mobile devices changes. The Mega uses this to drive the lobby
 LED feedback and to know how many seats are filled. */
typedef struct _catan_PlayerPresence {
    uint32_t proto_version;
    uint32_t connected_mask; /* bit i set => slot i has a phone connected */
    /* Stable client_id per slot (empty string if the slot is vacant). Lets
 the Mega log which devices are seated where without needing its own
 BLE stack. */
    pb_size_t client_ids_count;
    char client_ids[4][40];
} catan_PlayerPresence;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _catan_GamePhase_MIN catan_GamePhase_PHASE_LOBBY
#define _catan_GamePhase_MAX catan_GamePhase_PHASE_GAME_OVER
#define _catan_GamePhase_ARRAYSIZE ((catan_GamePhase)(catan_GamePhase_PHASE_GAME_OVER+1))

#define _catan_PlayerAction_MIN catan_PlayerAction_ACTION_NONE
#define _catan_PlayerAction_MAX catan_PlayerAction_ACTION_REPORT
#define _catan_PlayerAction_ARRAYSIZE ((catan_PlayerAction)(catan_PlayerAction_ACTION_REPORT+1))

#define catan_BoardState_phase_ENUMTYPE catan_GamePhase

#define catan_PlayerInput_action_ENUMTYPE catan_PlayerAction



/* Initializer values for message structs */
#define catan_BoardState_init_default            {0, _catan_GamePhase_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define catan_PlayerInput_init_default           {0, 0, _catan_PlayerAction_MIN, "", 0, 0, 0, 0, 0, 0}
#define catan_PlayerPresence_init_default        {0, 0, 0, {"", "", "", ""}}
#define catan_BoardState_init_zero               {0, _catan_GamePhase_MIN, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, {0, {0}}, 0, {0, 0, 0, 0}, 0, {0, 0, 0, 0}}
#define catan_PlayerInput_init_zero              {0, 0, _catan_PlayerAction_MIN, "", 0, 0, 0, 0, 0, 0}
#define catan_PlayerPresence_init_zero           {0, 0, 0, {"", "", "", ""}}

/* Field tags (for use in manual encoding/decoding) */
#define catan_BoardState_proto_version_tag       1
#define catan_BoardState_phase_tag               2
#define catan_BoardState_num_players_tag         3
#define catan_BoardState_current_player_tag      4
#define catan_BoardState_setup_round_tag         5
#define catan_BoardState_has_rolled_tag          6
#define catan_BoardState_die1_tag                7
#define catan_BoardState_die2_tag                8
#define catan_BoardState_reveal_number_tag       9
#define catan_BoardState_winner_id_tag           10
#define catan_BoardState_robber_tile_tag         11
#define catan_BoardState_connected_mask_tag      12
#define catan_BoardState_tiles_packed_tag        13
#define catan_BoardState_vp_tag                  14
#define catan_BoardState_ready_tag               15
#define catan_PlayerInput_proto_version_tag      1
#define catan_PlayerInput_player_id_tag          2
#define catan_PlayerInput_action_tag             3
#define catan_PlayerInput_client_id_tag          4
#define catan_PlayerInput_vp_tag                 10
#define catan_PlayerInput_res_lumber_tag         11
#define catan_PlayerInput_res_wool_tag           12
#define catan_PlayerInput_res_grain_tag          13
#define catan_PlayerInput_res_brick_tag          14
#define catan_PlayerInput_res_ore_tag            15
#define catan_PlayerPresence_proto_version_tag   1
#define catan_PlayerPresence_connected_mask_tag  2
#define catan_PlayerPresence_client_ids_tag      3

/* Struct field encoding specification for nanopb */
#define catan_BoardState_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_version,     1) \
X(a, STATIC,   SINGULAR, UENUM,    phase,             2) \
X(a, STATIC,   SINGULAR, UINT32,   num_players,       3) \
X(a, STATIC,   SINGULAR, UINT32,   current_player,    4) \
X(a, STATIC,   SINGULAR, UINT32,   setup_round,       5) \
X(a, STATIC,   SINGULAR, BOOL,     has_rolled,        6) \
X(a, STATIC,   SINGULAR, UINT32,   die1,              7) \
X(a, STATIC,   SINGULAR, UINT32,   die2,              8) \
X(a, STATIC,   SINGULAR, UINT32,   reveal_number,     9) \
X(a, STATIC,   SINGULAR, UINT32,   winner_id,        10) \
X(a, STATIC,   SINGULAR, UINT32,   robber_tile,      11) \
X(a, STATIC,   SINGULAR, UINT32,   connected_mask,   12) \
X(a, STATIC,   SINGULAR, BYTES,    tiles_packed,     13) \
X(a, STATIC,   REPEATED, UINT32,   vp,               14) \
X(a, STATIC,   REPEATED, UINT32,   ready,            15)
#define catan_BoardState_CALLBACK NULL
#define catan_BoardState_DEFAULT NULL

#define catan_PlayerInput_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_version,     1) \
X(a, STATIC,   SINGULAR, UINT32,   player_id,         2) \
X(a, STATIC,   SINGULAR, UENUM,    action,            3) \
X(a, STATIC,   SINGULAR, STRING,   client_id,         4) \
X(a, STATIC,   SINGULAR, UINT32,   vp,               10) \
X(a, STATIC,   SINGULAR, UINT32,   res_lumber,       11) \
X(a, STATIC,   SINGULAR, UINT32,   res_wool,         12) \
X(a, STATIC,   SINGULAR, UINT32,   res_grain,        13) \
X(a, STATIC,   SINGULAR, UINT32,   res_brick,        14) \
X(a, STATIC,   SINGULAR, UINT32,   res_ore,          15)
#define catan_PlayerInput_CALLBACK NULL
#define catan_PlayerInput_DEFAULT NULL

#define catan_PlayerPresence_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   proto_version,     1) \
X(a, STATIC,   SINGULAR, UINT32,   connected_mask,    2) \
X(a, STATIC,   REPEATED, STRING,   client_ids,        3)
#define catan_PlayerPresence_CALLBACK NULL
#define catan_PlayerPresence_DEFAULT NULL

extern const pb_msgdesc_t catan_BoardState_msg;
extern const pb_msgdesc_t catan_PlayerInput_msg;
extern const pb_msgdesc_t catan_PlayerPresence_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define catan_BoardState_fields &catan_BoardState_msg
#define catan_PlayerInput_fields &catan_PlayerInput_msg
#define catan_PlayerPresence_fields &catan_PlayerPresence_msg

/* Maximum encoded size of messages (where known) */
#define CATAN_CATAN_PB_H_MAX_SIZE                catan_PlayerPresence_size
#define catan_BoardState_size                    133
#define catan_PlayerInput_size                   91
#define catan_PlayerPresence_size                176

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
