/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "catan.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(catan_BoardState, catan_BoardState, 2)


PB_BIND(catan_PlayerInput, catan_PlayerInput, AUTO)


PB_BIND(catan_PlayerPresence, catan_PlayerPresence, AUTO)











