[env:mega]
platform = atmelavr
board = megaatmega2560
framework = arduino

build_flags =
    -DBUFFER_LENGTH=128
    -DTWI_BUFFER_LENGTH=128

lib_deps =
    fastled/FastLED @ ^3.9.15
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.9

monitor_speed = 115200
