// =============================================================================
// board_topology.cpp — Catan board graph data and randomization.
//
// *** TOPOLOGY TABLES ***
// Generated by tools/generate_topology.py for a standard 19-tile board.
// Axial hex coordinates (q, r) with pointy-top orientation.
//
// Corner/edge ordering is clockwise from North:
//   Corners: 0=N  1=NE  2=SE  3=S  4=SW  5=NW
//   Edges:   0=NE 1=E   2=SE  3=SW 4=W   5=NW
//
// NONE (0xFF) marks unused slots (border tiles have < 6 neighbors, coastal
// vertices touch < 3 tiles, coastal edges border only 1 tile).
// =============================================================================

#include "board_topology.h"
#include "board_types.h"
#include <Arduino.h>
#include <string.h>

// ── Human-readable names ────────────────────────────────────────────────────

const char* biomeName(Biome b) {
    switch (b) {
        case Biome::FOREST:   return "Forest";
        case Biome::PASTURE:  return "Pasture";
        case Biome::FIELD:    return "Field";
        case Biome::HILL:     return "Hill";
        case Biome::MOUNTAIN: return "Mountain";
        case Biome::DESERT:   return "Desert";
        default:              return "?";
    }
}

const char* portName(PortType p) {
    switch (p) {
        case PortType::GENERIC_3_1: return "3:1";
        case PortType::LUMBER_2_1:  return "Lumber 2:1";
        case PortType::WOOL_2_1:    return "Wool 2:1";
        case PortType::GRAIN_2_1:   return "Grain 2:1";
        case PortType::BRICK_2_1:   return "Brick 2:1";
        case PortType::ORE_2_1:     return "Ore 2:1";
        case PortType::PORT_NONE:   return "None";
        default:                    return "?";
    }
}

// ┌─────────────────────────────────────────────────────────────────────────┐
// │  AUTO-GENERATED by tools/generate_topology.py                          │
// │  Tiles: 19   Vertices: 54   Edges: 72   Ports: 9                      │
// │  Coastal edges: 30   Coastal vertices: 30                              │
// │                                                                        │
// │  Hex layout (axial q,r — pointy-top):                                  │
// │                                                                        │
// │              T15(0,-2)  T16(1,-2)  T17(2,-2)                           │
// │          T14(-1,-1) T05(0,-1) T06(1,-1) T18(2,-1)                     │
// │      T13(-2,0) T04(-1,0) T00(0,0) T01(1,0) T07(2,0)                  │
// │          T12(-2,1) T03(-1,1) T02(0,1) T08(1,1)                        │
// │              T11(-2,2) T10(-1,2) T09(0,2)                              │
// └─────────────────────────────────────────────────────────────────────────┘

// ── Tile Topology ───────────────────────────────────────────────────────────
//   id   (q, r)       vertices[6] (CW from N)       edges[6] (CW from N)           neighbors (up to 6)
const TileDef TILE_TOPO[TILE_COUNT] = {
    /* T00 */ {  0, { 0, 0}, {  0,  1,  2,  3,  4,  5}, {  0,  1,  2,  3,  4,  5}, {   1,   2,   3,   4,   5,   6} },
    /* T01 */ {  1, { 1, 0}, {  6,  7,  8,  9,  2,  1}, {  6,  7,  8,  9,  1, 10}, {   0,   2,   6,   7,   8,  18} },
    /* T02 */ {  2, { 0, 1}, { 10, 11,  6,  1,  0, 12}, { 11, 12, 10,  0, 13, 14}, {   0,   1,   3,   8,   9,  10} },
    /* T03 */ {  3, {-1, 1}, { 13, 12,  0,  5, 14, 15}, { 15, 13,  5, 16, 17, 18}, {   0,   2,   4,  10,  11,  12} },
    /* T04 */ {  4, {-1, 0}, { 14,  5,  4, 16, 17, 18}, { 16,  4, 19, 20, 21, 22}, {   0,   3,   5,  12,  13,  14} },
    /* T05 */ {  5, { 0,-1}, {  4,  3, 19, 20, 21, 16}, {  3, 23, 24, 25, 26, 19}, {   0,   4,   6,  14,  15,  16} },
    /* T06 */ {  6, { 1,-1}, {  2,  9, 22, 23, 19,  3}, {  9, 27, 28, 29, 23,  2}, {   0,   1,   5,  16,  17,  18} },
    /* T07 */ {  7, { 2, 0}, { 24, 25, 26, 27,  8,  7}, { 30, 31, 32, 33,  7, 34}, {   1,   8,  18,NONE,NONE,NONE} },
    /* T08 */ {  8, { 1, 1}, { 28, 29, 24,  7,  6, 11}, { 35, 36, 34,  6, 12, 37}, {   1,   2,   7,   9,NONE,NONE} },
    /* T09 */ {  9, { 0, 2}, { 30, 31, 28, 11, 10, 32}, { 38, 39, 37, 11, 40, 41}, {   2,   8,  10,NONE,NONE,NONE} },
    /* T10 */ { 10, {-1, 2}, { 33, 32, 10, 12, 13, 34}, { 42, 40, 14, 15, 43, 44}, {   2,   3,   9,  11,NONE,NONE} },
    /* T11 */ { 11, {-2, 2}, { 35, 34, 13, 15, 36, 37}, { 45, 43, 18, 46, 47, 48}, {   3,  10,  12,NONE,NONE,NONE} },
    /* T12 */ { 12, {-2, 1}, { 36, 15, 14, 18, 38, 39}, { 46, 17, 22, 49, 50, 51}, {   3,   4,  11,  13,NONE,NONE} },
    /* T13 */ { 13, {-2, 0}, { 38, 18, 17, 40, 41, 42}, { 49, 21, 52, 53, 54, 55}, {   4,  12,  14,NONE,NONE,NONE} },
    /* T14 */ { 14, {-1,-1}, { 17, 16, 21, 43, 44, 40}, { 20, 26, 56, 57, 58, 52}, {   4,   5,  13,  15,NONE,NONE} },
    /* T15 */ { 15, { 0,-2}, { 21, 20, 45, 46, 47, 43}, { 25, 59, 60, 61, 62, 56}, {   5,  14,  16,NONE,NONE,NONE} },
    /* T16 */ { 16, { 1,-2}, { 19, 23, 48, 49, 45, 20}, { 29, 63, 64, 65, 59, 24}, {   5,   6,  15,  17,NONE,NONE} },
    /* T17 */ { 17, { 2,-2}, { 22, 50, 51, 52, 48, 23}, { 66, 67, 68, 69, 63, 28}, {   6,  16,  18,NONE,NONE,NONE} },
    /* T18 */ { 18, { 2,-1}, {  8, 27, 53, 50, 22,  9}, { 33, 70, 71, 66, 27,  8}, {   1,   6,   7,  17,NONE,NONE} },
};

// ── Vertex Topology ─────────────────────────────────────────────────────────
//   id    tiles (up to 3)     edges (up to 3)
const VertexDef VERTEX_TOPO[VERTEX_COUNT] = {
    /* V00 */ {  0, {   0,   2,   3}, {   0,   5,  13} },
    /* V01 */ {  1, {   0,   1,   2}, {   0,   1,  10} },
    /* V02 */ {  2, {   0,   1,   6}, {   1,   2,   9} },
    /* V03 */ {  3, {   0,   5,   6}, {   2,   3,  23} },
    /* V04 */ {  4, {   0,   4,   5}, {   3,   4,  19} },
    /* V05 */ {  5, {   0,   3,   4}, {   4,   5,  16} },
    /* V06 */ {  6, {   1,   2,   8}, {   6,  10,  12} },
    /* V07 */ {  7, {   1,   7,   8}, {   6,   7,  34} },
    /* V08 */ {  8, {   1,   7,  18}, {   7,   8,  33} },
    /* V09 */ {  9, {   1,   6,  18}, {   8,   9,  27} },
    /* V10 */ { 10, {   2,   9,  10}, {  11,  14,  40} },
    /* V11 */ { 11, {   2,   8,   9}, {  11,  12,  37} },
    /* V12 */ { 12, {   2,   3,  10}, {  13,  14,  15} },
    /* V13 */ { 13, {   3,  10,  11}, {  15,  18,  43} },
    /* V14 */ { 14, {   3,   4,  12}, {  16,  17,  22} },
    /* V15 */ { 15, {   3,  11,  12}, {  17,  18,  46} },
    /* V16 */ { 16, {   4,   5,  14}, {  19,  20,  26} },
    /* V17 */ { 17, {   4,  13,  14}, {  20,  21,  52} },
    /* V18 */ { 18, {   4,  12,  13}, {  21,  22,  49} },
    /* V19 */ { 19, {   5,   6,  16}, {  23,  24,  29} },
    /* V20 */ { 20, {   5,  15,  16}, {  24,  25,  59} },
    /* V21 */ { 21, {   5,  14,  15}, {  25,  26,  56} },
    /* V22 */ { 22, {   6,  17,  18}, {  27,  28,  66} },
    /* V23 */ { 23, {   6,  16,  17}, {  28,  29,  63} },
    /* V24 */ { 24, {   7,   8,NONE}, {  30,  34,  36} },
    /* V25 */ { 25, {   7,NONE,NONE}, {  30,  31,NONE} },
    /* V26 */ { 26, {   7,NONE,NONE}, {  31,  32,NONE} },
    /* V27 */ { 27, {   7,  18,NONE}, {  32,  33,  70} },
    /* V28 */ { 28, {   8,   9,NONE}, {  35,  37,  39} },
    /* V29 */ { 29, {   8,NONE,NONE}, {  35,  36,NONE} },
    /* V30 */ { 30, {   9,NONE,NONE}, {  38,  41,NONE} },
    /* V31 */ { 31, {   9,NONE,NONE}, {  38,  39,NONE} },
    /* V32 */ { 32, {   9,  10,NONE}, {  40,  41,  42} },
    /* V33 */ { 33, {  10,NONE,NONE}, {  42,  44,NONE} },
    /* V34 */ { 34, {  10,  11,NONE}, {  43,  44,  45} },
    /* V35 */ { 35, {  11,NONE,NONE}, {  45,  48,NONE} },
    /* V36 */ { 36, {  11,  12,NONE}, {  46,  47,  51} },
    /* V37 */ { 37, {  11,NONE,NONE}, {  47,  48,NONE} },
    /* V38 */ { 38, {  12,  13,NONE}, {  49,  50,  55} },
    /* V39 */ { 39, {  12,NONE,NONE}, {  50,  51,NONE} },
    /* V40 */ { 40, {  13,  14,NONE}, {  52,  53,  58} },
    /* V41 */ { 41, {  13,NONE,NONE}, {  53,  54,NONE} },
    /* V42 */ { 42, {  13,NONE,NONE}, {  54,  55,NONE} },
    /* V43 */ { 43, {  14,  15,NONE}, {  56,  57,  62} },
    /* V44 */ { 44, {  14,NONE,NONE}, {  57,  58,NONE} },
    /* V45 */ { 45, {  15,  16,NONE}, {  59,  60,  65} },
    /* V46 */ { 46, {  15,NONE,NONE}, {  60,  61,NONE} },
    /* V47 */ { 47, {  15,NONE,NONE}, {  61,  62,NONE} },
    /* V48 */ { 48, {  16,  17,NONE}, {  63,  64,  69} },
    /* V49 */ { 49, {  16,NONE,NONE}, {  64,  65,NONE} },
    /* V50 */ { 50, {  17,  18,NONE}, {  66,  67,  71} },
    /* V51 */ { 51, {  17,NONE,NONE}, {  67,  68,NONE} },
    /* V52 */ { 52, {  17,NONE,NONE}, {  68,  69,NONE} },
    /* V53 */ { 53, {  18,NONE,NONE}, {  70,  71,NONE} },
};

// ── Edge Topology ───────────────────────────────────────────────────────────
//   id   vertices      tiles (up to 2)
const EdgeDef EDGE_TOPO[EDGE_COUNT] = {
    /* E00 */ {  0, {  0,  1}, {   0,   2} },
    /* E01 */ {  1, {  1,  2}, {   0,   1} },
    /* E02 */ {  2, {  2,  3}, {   0,   6} },
    /* E03 */ {  3, {  3,  4}, {   0,   5} },
    /* E04 */ {  4, {  4,  5}, {   0,   4} },
    /* E05 */ {  5, {  0,  5}, {   0,   3} },
    /* E06 */ {  6, {  6,  7}, {   1,   8} },
    /* E07 */ {  7, {  7,  8}, {   1,   7} },
    /* E08 */ {  8, {  8,  9}, {   1,  18} },
    /* E09 */ {  9, {  2,  9}, {   1,   6} },
    /* E10 */ { 10, {  1,  6}, {   1,   2} },
    /* E11 */ { 11, { 10, 11}, {   2,   9} },
    /* E12 */ { 12, {  6, 11}, {   2,   8} },
    /* E13 */ { 13, {  0, 12}, {   2,   3} },
    /* E14 */ { 14, { 10, 12}, {   2,  10} },
    /* E15 */ { 15, { 12, 13}, {   3,  10} },
    /* E16 */ { 16, {  5, 14}, {   3,   4} },
    /* E17 */ { 17, { 14, 15}, {   3,  12} },
    /* E18 */ { 18, { 13, 15}, {   3,  11} },
    /* E19 */ { 19, {  4, 16}, {   4,   5} },
    /* E20 */ { 20, { 16, 17}, {   4,  14} },
    /* E21 */ { 21, { 17, 18}, {   4,  13} },
    /* E22 */ { 22, { 14, 18}, {   4,  12} },
    /* E23 */ { 23, {  3, 19}, {   5,   6} },
    /* E24 */ { 24, { 19, 20}, {   5,  16} },
    /* E25 */ { 25, { 20, 21}, {   5,  15} },
    /* E26 */ { 26, { 16, 21}, {   5,  14} },
    /* E27 */ { 27, {  9, 22}, {   6,  18} },
    /* E28 */ { 28, { 22, 23}, {   6,  17} },
    /* E29 */ { 29, { 19, 23}, {   6,  16} },
    /* E30 */ { 30, { 24, 25}, {   7,NONE} },
    /* E31 */ { 31, { 25, 26}, {   7,NONE} },
    /* E32 */ { 32, { 26, 27}, {   7,NONE} },
    /* E33 */ { 33, {  8, 27}, {   7,  18} },
    /* E34 */ { 34, {  7, 24}, {   7,   8} },
    /* E35 */ { 35, { 28, 29}, {   8,NONE} },
    /* E36 */ { 36, { 24, 29}, {   8,NONE} },
    /* E37 */ { 37, { 11, 28}, {   8,   9} },
    /* E38 */ { 38, { 30, 31}, {   9,NONE} },
    /* E39 */ { 39, { 28, 31}, {   9,NONE} },
    /* E40 */ { 40, { 10, 32}, {   9,  10} },
    /* E41 */ { 41, { 30, 32}, {   9,NONE} },
    /* E42 */ { 42, { 32, 33}, {  10,NONE} },
    /* E43 */ { 43, { 13, 34}, {  10,  11} },
    /* E44 */ { 44, { 33, 34}, {  10,NONE} },
    /* E45 */ { 45, { 34, 35}, {  11,NONE} },
    /* E46 */ { 46, { 15, 36}, {  11,  12} },
    /* E47 */ { 47, { 36, 37}, {  11,NONE} },
    /* E48 */ { 48, { 35, 37}, {  11,NONE} },
    /* E49 */ { 49, { 18, 38}, {  12,  13} },
    /* E50 */ { 50, { 38, 39}, {  12,NONE} },
    /* E51 */ { 51, { 36, 39}, {  12,NONE} },
    /* E52 */ { 52, { 17, 40}, {  13,  14} },
    /* E53 */ { 53, { 40, 41}, {  13,NONE} },
    /* E54 */ { 54, { 41, 42}, {  13,NONE} },
    /* E55 */ { 55, { 38, 42}, {  13,NONE} },
    /* E56 */ { 56, { 21, 43}, {  14,  15} },
    /* E57 */ { 57, { 43, 44}, {  14,NONE} },
    /* E58 */ { 58, { 40, 44}, {  14,NONE} },
    /* E59 */ { 59, { 20, 45}, {  15,  16} },
    /* E60 */ { 60, { 45, 46}, {  15,NONE} },
    /* E61 */ { 61, { 46, 47}, {  15,NONE} },
    /* E62 */ { 62, { 43, 47}, {  15,NONE} },
    /* E63 */ { 63, { 23, 48}, {  16,  17} },
    /* E64 */ { 64, { 48, 49}, {  16,NONE} },
    /* E65 */ { 65, { 45, 49}, {  16,NONE} },
    /* E66 */ { 66, { 22, 50}, {  17,  18} },
    /* E67 */ { 67, { 50, 51}, {  17,NONE} },
    /* E68 */ { 68, { 51, 52}, {  17,NONE} },
    /* E69 */ { 69, { 48, 52}, {  17,NONE} },
    /* E70 */ { 70, { 27, 53}, {  18,NONE} },
    /* E71 */ { 71, { 50, 53}, {  18,NONE} },
};

// ── Port Topology ───────────────────────────────────────────────────────────
// Edit the `type` field to reconfigure which port goes where.
// The vertex pairs are fixed by the board geometry.
//   id   type                    vertices
const PortDef PORT_TOPO[PORT_COUNT] = {
    /* P0 */ { 0, PortType::GENERIC_3_1, { 24, 25} },
    /* P1 */ { 1, PortType::LUMBER_2_1,  { 27, 53} },
    /* P2 */ { 2, PortType::GENERIC_3_1, { 48, 52} },
    /* P3 */ { 3, PortType::WOOL_2_1,    { 45, 46} },
    /* P4 */ { 4, PortType::GENERIC_3_1, { 43, 44} },
    /* P5 */ { 5, PortType::GRAIN_2_1,   { 38, 42} },
    /* P6 */ { 6, PortType::BRICK_2_1,   { 36, 37} },
    /* P7 */ { 7, PortType::GENERIC_3_1, { 33, 34} },
    /* P8 */ { 8, PortType::ORE_2_1,     { 28, 31} },
};

// ── Runtime tile state ──────────────────────────────────────────────────────

TileState g_tile_state[TILE_COUNT];

// ── Adjacency helpers ───────────────────────────────────────────────────────

uint8_t tilesForVertex(uint8_t vertex_id, uint8_t out[], uint8_t max_out) {
    if (vertex_id >= VERTEX_COUNT) return 0;
    uint8_t count = 0;
    for (uint8_t i = 0; i < 3 && count < max_out; ++i) {
        uint8_t tid = VERTEX_TOPO[vertex_id].tiles[i];
        if (tid != NONE) out[count++] = tid;
    }
    return count;
}

uint8_t tilesForEdge(uint8_t edge_id, uint8_t out[], uint8_t max_out) {
    if (edge_id >= EDGE_COUNT) return 0;
    uint8_t count = 0;
    for (uint8_t i = 0; i < 2 && count < max_out; ++i) {
        uint8_t tid = EDGE_TOPO[edge_id].tiles[i];
        if (tid != NONE) out[count++] = tid;
    }
    return count;
}

// ── Randomization ───────────────────────────────────────────────────────────

static void shuffleArray(uint8_t* arr, uint8_t n) {
    for (uint8_t i = n - 1; i > 0; --i) {
        uint8_t j = random(0, i + 1);
        uint8_t tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }
}

void randomizeBoardLayout() {
    // Standard Catan biome distribution:
    // 4 Forest, 4 Pasture, 4 Field, 3 Hill, 3 Mountain, 1 Desert = 19
    uint8_t biomes[TILE_COUNT];
    uint8_t idx = 0;
    for (uint8_t i = 0; i < 4; ++i) biomes[idx++] = (uint8_t)Biome::FOREST;
    for (uint8_t i = 0; i < 4; ++i) biomes[idx++] = (uint8_t)Biome::PASTURE;
    for (uint8_t i = 0; i < 4; ++i) biomes[idx++] = (uint8_t)Biome::FIELD;
    for (uint8_t i = 0; i < 3; ++i) biomes[idx++] = (uint8_t)Biome::HILL;
    for (uint8_t i = 0; i < 3; ++i) biomes[idx++] = (uint8_t)Biome::MOUNTAIN;
    biomes[idx++] = (uint8_t)Biome::DESERT;

    shuffleArray(biomes, TILE_COUNT);

    // Standard number tokens (18 for 18 non-desert tiles):
    // 1×2, 2×3, 2×4, 2×5, 2×6, 2×8, 2×9, 2×10, 2×11, 1×12
    uint8_t numbers[] = { 2, 3, 3, 4, 4, 5, 5, 6, 6, 8, 8, 9, 9, 10, 10, 11, 11, 12 };
    shuffleArray(numbers, 18);

    uint8_t num_idx = 0;
    for (uint8_t t = 0; t < TILE_COUNT; ++t) {
        g_tile_state[t].biome = (Biome)biomes[t];
        if (g_tile_state[t].biome == Biome::DESERT) {
            g_tile_state[t].number = 0;
        } else {
            g_tile_state[t].number = numbers[num_idx++];
        }
    }
}
